-- =========================================================
-- TASK 3: SQL FOR DATA ANALYSIS
-- Ecommerce Database
-- Tool: Programiz Online SQL Compiler / SQLite
-- =========================================================


-- 1. SELECT
-- Display all customers

SELECT *
FROM Customers;


-- =========================================================
-- 2. WHERE
-- Find customers who live in Kolkata

SELECT *
FROM Customers
WHERE city = 'Kolkata';


-- =========================================================
-- 3. ORDER BY
-- Display products from highest price to lowest price

SELECT *
FROM Products
ORDER BY price DESC;


-- =========================================================
-- 4. GROUP BY
-- Count the number of orders placed by each customer

SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM Orders
GROUP BY customer_id;


-- =========================================================
-- 5. AGGREGATE FUNCTIONS
-- Calculate total and average product price

SELECT
    SUM(price) AS total_price,
    AVG(price) AS average_price
FROM Products;


-- =========================================================
-- 6. INNER JOIN
-- Display customer name, product name and quantity

SELECT
    Customers.customer_name,
    Products.product_name,
    Orders.quantity
FROM Orders
INNER JOIN Customers
    ON Orders.customer_id = Customers.customer_id
INNER JOIN Products
    ON Orders.product_id = Products.product_id;


-- =========================================================
-- 7. LEFT JOIN
-- Display all customers and their orders

SELECT
    Customers.customer_name,
    Orders.order_id
FROM Customers
LEFT JOIN Orders
    ON Customers.customer_id = Orders.customer_id;


-- =========================================================
-- 8. SUBQUERY
-- Find products whose price is greater than
-- the average product price

SELECT
    product_name,
    price
FROM Products
WHERE price > (
    SELECT AVG(price)
    FROM Products
);


-- =========================================================
-- 9. PRODUCT REVENUE ANALYSIS
-- Calculate revenue generated by each product
-- Revenue = Quantity × Product Price

SELECT
    Products.product_name,
    SUM(Orders.quantity * Products.price) AS revenue
FROM Orders
JOIN Products
    ON Orders.product_id = Products.product_id
GROUP BY Products.product_name
ORDER BY revenue DESC;


-- =========================================================
-- 10. CUSTOMER REVENUE ANALYSIS
-- Calculate total revenue generated by each customer

SELECT
    Customers.customer_name,
    SUM(Orders.quantity * Products.price) AS total_revenue
FROM Orders
JOIN Customers
    ON Orders.customer_id = Customers.customer_id
JOIN Products
    ON Orders.product_id = Products.product_id
GROUP BY Customers.customer_name
ORDER BY total_revenue DESC;


-- =========================================================
-- 11. CREATE A VIEW
-- Create a view showing customer-wise revenue

CREATE VIEW customer_revenue AS
SELECT
    Customers.customer_name,
    SUM(Orders.quantity * Products.price) AS total_revenue
FROM Orders
JOIN Customers
    ON Orders.customer_id = Customers.customer_id
JOIN Products
    ON Orders.product_id = Products.product_id
GROUP BY Customers.customer_name;


-- Display the created view

SELECT *
FROM customer_revenue;


-- =========================================================
-- 12. CREATE AN INDEX
-- Create an index on customer_id in Orders table

CREATE INDEX idx_orders_customer
ON Orders(customer_id);


-- Check the created index

PRAGMA index_list('Orders');


-- =========================================================
-- END OF TASK 3
-- =========================================================